{
 "title": "MySQL NDB Cluster Dashboard",
 "description": "https://github.com/sseyren/mysqld_ndb_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(mysql_up,job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mysql_up,instance)"
    }
   },
   {
    "name": "node_id",
    "label": "Node ID",
    "query": {
     "query": "label_values(mysql_ndbinfo_nodes_status,node_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Node Uptime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_ndbinfo_nodes_uptime{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Data Node Status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_nodes_status{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "Node: {{node_id}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Data Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mysql_ndbinfo_memoryusage_used{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", memory_type=\"Data memory\"}\n/\nmysql_ndbinfo_memoryusage_total{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", memory_type=\"Data memory\"}",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Index Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mysql_ndbinfo_memoryusage_used{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", memory_type=\"Index memory\"}\n/\nmysql_ndbinfo_memoryusage_total{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", memory_type=\"Index memory\"}",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Disk Data File Usage by File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum by(job, instance, file_id, file_name, file_type, tablespace, logfile_group) (\n    mysql_ndbinfo_files_free_extents{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", file_type=\"DATAFILE\"\n    }\n  )\n  /\n  sum by(job, instance, file_id, file_name, file_type, tablespace, logfile_group) (\n    mysql_ndbinfo_files_total_extents{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", file_type=\"DATAFILE\"\n    }\n  )\n)",
     "legendFormat": "[{{logfile_group}} {{tablespace}}] {{file_name}}"
    }
   ]
  },
  {
   "title": "Disk Data File Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum by(job, instance, node_id, tablespace, logfile_group) (\n    mysql_ndbinfo_files_free_extents{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", file_type=\"DATAFILE\"\n    }\n  )\n  /\n  sum by(job, instance, node_id, tablespace, logfile_group) (\n    mysql_ndbinfo_files_total_extents{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", file_type=\"DATAFILE\"\n    }\n  )\n)",
     "legendFormat": "[{{logfile_group}} {{tablespace}}] Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Undo Log File Usage by File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum by(job, instance, file_id, file_name, file_type, logfile_group) (\n    mysql_ndbinfo_files_free_extents{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", file_type=\"UNDO LOG\"\n    }\n  )\n  /\n  sum by(job, instance, file_id, file_name, file_type, logfile_group) (\n    mysql_ndbinfo_files_total_extents{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", file_type=\"UNDO LOG\"\n    }\n  )\n)",
     "legendFormat": "[{{logfile_group}}] {{file_name}}"
    }
   ]
  },
  {
   "title": "Undo Log File Usage by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum by(job, instance, node_id, logfile_group) (\n    mysql_ndbinfo_files_free_extents{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", file_type=\"UNDO LOG\"\n    }\n  )\n  /\n  sum by(job, instance, node_id, logfile_group) (\n    mysql_ndbinfo_files_total_extents{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\", file_type=\"UNDO LOG\"\n    }\n  )\n)",
     "legendFormat": "[{{logfile_group}}] Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Logbuffer Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, log_type, log_id) (\n  mysql_ndbinfo_logbuffers_bytes_used{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)\n/\nsum by(job, instance, node_id, log_type, log_id) (\n  mysql_ndbinfo_logbuffers_bytes_total{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)",
     "legendFormat": "[n{{node_id}}] {{log_type}} {{log_id}}"
    }
   ]
  },
  {
   "title": "Logspace Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, log_type, log_id) (\n  mysql_ndbinfo_logspaces_bytes_used{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)\n/\nsum by(job, instance, node_id, log_type, log_id) (\n  mysql_ndbinfo_logspaces_bytes_total{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)",
     "legendFormat": "[n{{node_id}}] {{log_type}} {{log_id}}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mysql_ndbinfo_resources_used{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n/\nmysql_ndbinfo_resources_reserved{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "[n{{node_id}}] {{resource_name}}"
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job, instance, block_name, pool_name) (\n  mysql_ndbinfo_pools_used{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)\n/\nsum by(job, instance, block_name, pool_name) (\n  mysql_ndbinfo_pools_total{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)",
     "legendFormat": "{{block_name}} {{pool_name}}"
    }
   ]
  },
  { "title": "Transactions & Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Transactions by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (job, instance, node_id) (\n  mysql_ndbinfo_cluster_transactions_count{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Operations by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (job, instance, node_id) (\n  mysql_ndbinfo_cluster_operations_count{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Transactions by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (job, instance, state) (\n  mysql_ndbinfo_cluster_transactions_count{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Operations by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (job, instance, operation_type) (\n  mysql_ndbinfo_cluster_operations_count{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Longest Inactive Transaction Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mysql_ndbinfo_cluster_transactions_max_inactive_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (job, instance, state) (\n  mysql_ndbinfo_cluster_operations_count{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}\n)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DBTC: Transaction Coordinator Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 }
  },
  {
   "title": "Duration Of Successful Scans",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_scans_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of Failed Scans",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_scan_errors_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of Successful Fragment Scans",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_scan_fragments_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of Failed Fragment Scans",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_scan_fragment_errors_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of Successful Transactions",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_transactions_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of Failed Transactions",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_transaction_errors_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of Successful Primary Key Reads",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_read_key_ops_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of Successful Primary Key Writes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_write_key_ops_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of Successful Unique Index Key Operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_index_key_ops_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Of All Failed Key Read Or Write Operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_tc_time_track_stats_key_op_errors_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk Write Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Disk Write Speed of REDO Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_disk_write_speed_redo_bytes{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Disk Write Speed of LCP Backup Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_disk_write_speed_backup_lcp_bytes{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Disk Page Buffer Usage by NDB Cluster Disk Data Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 }
  },
  {
   "title": "Pages Read From Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_diskpagebuffer_pages_read{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Pages Written to Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_diskpagebuffer_pages_written{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Requests For Pages That Were Available In Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_diskpagebuffer_page_requests_direct_return{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Pages Written By Local Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_diskpagebuffer_pages_written_lcp{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Requests That Had To Wait For Pages To Become Available In Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_diskpagebuffer_page_requests_wait_queue{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Page Writes Waiting For Log To Be Written To Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_diskpagebuffer_log_waits{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Requests For Pages That Were Unavailable In Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_diskpagebuffer_page_requests_wait_io{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Read From Buffer Hit-Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  mysql_ndbinfo_diskpagebuffer_page_requests_direct_return{\n    job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n  }\n)\n/\nsum by(job, instance, node_id) (\n  mysql_ndbinfo_diskpagebuffer_page_requests_direct_return{\n    job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n  }\n  +\n  mysql_ndbinfo_diskpagebuffer_page_requests_wait_io{\n    job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n  }\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "PGMAN: Page and Buffer Management Block for Disk Data Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 }
  },
  {
   "title": "Disk Data Tablespace Page Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_pgman_time_track_stats_page_reads_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Data Tablespace Page Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_pgman_time_track_stats_page_writes_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Data Tablespace Log Wait Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_pgman_time_track_stats_log_waits_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Data Tablespace get_page() Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
   "targets": [
    {
     "expr": "sum by(job, instance, le) (\n  rate(\n    mysql_ndbinfo_pgman_time_track_stats_get_page_calls_bucket{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Membership / Arbitrator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "Connection to Arbitrator Node",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 190 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_membership_arb_connected{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "Node: {{node_id}}"
    }
   ]
  },
  {
   "title": "Arbitrator State",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 190 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_membership_arb_state{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Arbitrator Node",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 200 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_membership_arbitrator{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "President Node",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 200 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_membership_president{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Successor Node",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 200 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_membership_successor{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  { "title": "Transporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 210 } },
  {
   "title": "Transporters Send/Receive Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(\n  mysql_ndbinfo_transporters_bytes_received{\n    job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n  }[$__rate_interval]\n)",
     "legendFormat": "RX {{node_id}} ← {{remote_node_id}}"
    },
    {
     "expr": "increase(\n  mysql_ndbinfo_transporters_bytes_sent{\n    job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n  }[$__rate_interval]\n)",
     "legendFormat": "TX {{node_id}} → {{remote_node_id}}"
    }
   ]
  },
  {
   "title": "Transporter Status",
   "type": "state-timeline",
   "gridPos": { "h": 21, "w": 10, "x": 0, "y": 219 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_transporters_status{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "{{node_id}} → {{remote_node_id}}"
    }
   ]
  },
  {
   "title": "Transporter Overloaded?",
   "type": "state-timeline",
   "gridPos": { "h": 21, "w": 7, "x": 10, "y": 219 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_transporters_overloaded{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "{{node_id}} → {{remote_node_id}}"
    }
   ]
  },
  {
   "title": "Transporter Slowdown?",
   "type": "state-timeline",
   "gridPos": { "h": 21, "w": 7, "x": 17, "y": 219 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_transporters_slowdown{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "{{node_id}} → {{remote_node_id}}"
    }
   ]
  },
  { "title": "Counters DBLQH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 240 } },
  {
   "title": "DBLQH LQHKEY_OVERLOAD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBLQH\", counter_name=\"LQHKEY_OVERLOAD\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBLQH LQHKEY_OVERLOAD_NODE_PEER",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBLQH\", counter_name=\"LQHKEY_OVERLOAD_NODE_PEER\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBLQH LQHKEY_OVERLOAD_READER",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBLQH\", counter_name=\"LQHKEY_OVERLOAD_READER\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBLQH LQHKEY_OVERLOAD_SUBSCRIBER",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBLQH\", counter_name=\"LQHKEY_OVERLOAD_SUBSCRIBER\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBLQH LQHKEY_OVERLOAD_TC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBLQH\", counter_name=\"LQHKEY_OVERLOAD_TC\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBLQH LQHSCAN_SLOWDOWNS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBLQH\", counter_name=\"LQHSCAN_SLOWDOWNS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBLQH OPERATIONS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBLQH\", counter_name=\"OPERATIONS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  { "title": "Counters DBSPJ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 255 } },
  {
   "title": "DBSPJ CONST_PRUNED_RANGE_SCANS_RECEIVED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"CONST_PRUNED_RANGE_SCANS_RECEIVED\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ LOCAL_RANGE_SCANS_SENT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"LOCAL_RANGE_SCANS_SENT\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ LOCAL_READS_SENT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"LOCAL_READS_SENT\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ LOCAL_TABLE_SCANS_SENT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"LOCAL_TABLE_SCANS_SENT\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ PRUNED_RANGE_SCANS_RECEIVED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"PRUNED_RANGE_SCANS_RECEIVED\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ RANGE_SCANS_RECEIVED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"RANGE_SCANS_RECEIVED\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ READS_NOT_FOUND",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"READS_NOT_FOUND\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ READS_RECEIVED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"READS_RECEIVED\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ REMOTE_RANGE_SCANS_SENT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"REMOTE_RANGE_SCANS_SENT\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ REMOTE_READS_SENT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"REMOTE_READS_SENT\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ SCAN_BATCHES_RETURNED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"SCAN_BATCHES_RETURNED\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ SCAN_ROWS_RETURNED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"SCAN_ROWS_RETURNED\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBSPJ TABLE_SCANS_RECEIVED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 277 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBSPJ\", counter_name=\"TABLE_SCANS_RECEIVED\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  { "title": "Counters DBTC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 284 } },
  {
   "title": "DBTC ABORTS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 285 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"ABORTS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC ATTRINFO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 285 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"ATTRINFO\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC COMMITS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 285 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"COMMITS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC LOCAL_READS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 285 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"LOCAL_READS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC LOCAL_WRITES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 292 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"LOCAL_WRITES\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC RANGE_SCANS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 292 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"RANGE_SCANS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC READS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 292 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"READS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC SIMPLE_READS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 292 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"SIMPLE_READS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC TABLE_SCANS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 299 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"TABLE_SCANS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC TRANSACTIONS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 299 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"TRANSACTIONS\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "DBTC WRITES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 299 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id, block_name, counter_name) (\n  increase(\n    mysql_ndbinfo_counters{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\",\n      block_name=\"DBTC\", counter_name=\"WRITES\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  { "title": "Thread Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 306 } },
  {
   "title": "Loops In Main Loop",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 307 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_loops{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Signals Executed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 307 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_signals_exec{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Times Waiting For Additional Input",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 307 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_waits{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Priority A Signals Sent To Own Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_signals_sent_local_prioa{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Priority B Signals Sent To Own Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_signals_sent_local_priob{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Priority A Signals Sent To Remote Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_signals_sent_remote_prioa{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "Priority B Signals Sent To Remote Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 314 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_signals_sent_remote_priob{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "OS Page Faults (Hard/Major Page Faults)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_os_majflt{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "OS Page Reclaims (Soft/Minor Page Faults)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_os_minflt{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "OS Voluntary Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_os_nvcsw{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  {
   "title": "OS Involuntary Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(job, instance, node_id) (\n  increase(\n    mysql_ndbinfo_threadstat_os_nivcsw{\n      job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "Node {{node_id}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 328 } },
  {
   "title": "Node Configuration Values",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 329 },
   "targets": [
    {
     "expr": "mysql_ndbinfo_config_value{job=~\"$job\", instance=~\"$instance\", node_id=~\"${node_id:regex}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}