{
 "title": "MySQL NDB API Node Dashboard",
 "description": "https://github.com/sseyren/mysqld_ndb_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(mysql_up,job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mysql_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions Started",
   "type": "timeseries",
   "description": "Number of transactions started.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_trans_start_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Committed",
   "type": "timeseries",
   "description": "Number of transactions committed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_trans_commit_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Aborted",
   "type": "timeseries",
   "description": "Number of transactions aborted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_trans_abort_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Closed",
   "type": "timeseries",
   "description": "Number of transactions aborted. (This value may be greater than the sum of TransCommitCount and TransAbortCount.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_trans_close_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Primary Key Operations",
   "type": "timeseries",
   "description": "Number of operations based on or using primary keys. This count includes blob-part table operations, implicit unlocking operations, and auto-increment operations, as well as primary key operations normally visible to MySQL clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_pk_op_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique Key Operations",
   "type": "timeseries",
   "description": "Number of operations based on or using unique keys.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_uk_op_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transmission", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bytes Sent To Data Nodes",
   "type": "timeseries",
   "description": "Amount of data (in bytes) sent to the data nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_bytes_sent_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received From Data Nodes",
   "type": "timeseries",
   "description": "Amount of data (in bytes) received from the data nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_bytes_received_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Waits / Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Wait Exec Complete Count",
   "type": "timeseries",
   "description": "Number of times thread has been blocked while waiting for execution of an operation to complete. Includes all execute() calls as well as implicit executes for blob operations and auto-increment not visible to clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_wait_exec_complete_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wait Scan Result Count",
   "type": "timeseries",
   "description": "Number of times thread has been blocked while waiting for a scan-based signal, such waiting for additional results, or for a scan to close.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_wait_scan_result_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wait Meta Request Count",
   "type": "timeseries",
   "description": "Number of times thread has been blocked waiting for a metadata-based signal; this can occur when waiting for a DDL operation or for an epoch to be started (or ended).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_wait_meta_request_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Signal Wait Duration",
   "type": "timeseries",
   "description": "Total time (in nanoseconds) spent waiting for some type of signal from the data nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_wait_nanos_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scans / Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Table Scans",
   "type": "timeseries",
   "description": "Number of table scans that have been started. This includes scans of internal tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_table_scan_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Range Scans",
   "type": "timeseries",
   "description": "Number of range scans that have been started.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_range_scan_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pruned Scans",
   "type": "timeseries",
   "description": "Number of scans that have been pruned to a single partition.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_pruned_scan_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Scans",
   "type": "timeseries",
   "description": "Number of batches of rows received. (A batch in this context is a set of scan results from a single fragment.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_scan_batch_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Rows",
   "type": "timeseries",
   "description": "Total number of rows that have been read. Includes rows read using primary key, unique key, and scan operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_read_row_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Local Read Rows",
   "type": "timeseries",
   "description": "Number of rows read from the data same node on which the transaction was being run.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_trans_local_read_row_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Received Data Events",
   "type": "timeseries",
   "description": "Number of row change events received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_event_data_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Non-Data Events",
   "type": "timeseries",
   "description": "Number of events received, other than row change events.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_event_nondata_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Of Events",
   "type": "timeseries",
   "description": "Number of bytes of events received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_event_bytes_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events (Binary Log Injector)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Received Data Events (Binary Log Injector)",
   "type": "timeseries",
   "description": "Number of row change events received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_event_data_count_injector{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Non-Data Events (Binary Log Injector)",
   "type": "timeseries",
   "description": "Number of events received, other than row change events.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_event_nondata_count_injector{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Of Events (Binary Log Injector)",
   "type": "timeseries",
   "description": "Number of bytes of events received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_event_bytes_count_injector{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Adaptive Send Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Adaptive Send Deferred Count",
   "type": "timeseries",
   "description": "Number of adaptive send calls that were not actually sent.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_adaptive_send_deferred_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adaptive Send Forced Count",
   "type": "timeseries",
   "description": "Number of adaptive send calls using forced-send sent by this MySQL Server (SQL node).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_adaptive_send_forced_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adaptive Send Unforced Count",
   "type": "timeseries",
   "description": "Number of adaptive send calls without forced-send sent by this MySQL server (SQL node).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "increase (\n  mysql_global_status_ndb_api_adaptive_send_unforced_count{\n    job=~\"$job\", instance=~\"$instance\"\n  }[$__rate_interval]\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}